### create user test
POST http://localhost:3005/auth/signup
content-type: application/json
 
{
    "email": "testtt@hotmail.com",
    "password": "mdp"
    
}

### signin user test
POST http://localhost:3005/auth/signin
content-type: application/json
 
{
    "email": "testt@hotmail.com",
    "password": "mdp"
    
}


### tester route get users
GET http://localhost:3005/auth


### tester route get user by id
GET http://localhost:3005/auth/9