### create user test
POST http://localhost:3005/auth/signup
content-type: application/json
 
{
    "email": "addmin@hotmail.com",
    "password": "mdp",
    "role": "admin"
    
}


### signin user test
POST http://localhost:3005/auth/signin
content-type: application/json
 
{
    "email": "addmin@hotmail.com",
    "password": "mdp"
    
}

### signout user test
POST http://localhost:3005/auth/signout
content-type: application/json
 
{
    "email": "addmin@hotmail.com",
    "password": "mdp"
    
}

### tester route get users
GET http://localhost:3005/auth/whoami


### tester route get users
GET http://localhost:3005/users


### tester route get user by id
GET http://localhost:3005/users/16

### tester route delete user en étant
DELETE http://localhost:3005/users/18

### Importation des cours depuis l'API 
POST http://localhost:3005/courses/import


### Activer pu désactiver un cours
PATCH http://localhost:3005/courses/2/toggle


### test create course
POST http://localhost:3005/courses
Content-Type: application/json

{
  "title": "Yogaa",
  "bodyPart": "Full body",
  "description": "Cours de yoga debutant",
  "gifUrl": "https://example.com/yoga.gif",
  "capacity": 15

}

### test get all courses
GET http://localhost:3005/courses

### tester route get course by id
GET http://localhost:3005/courses/3

### test update course
PATCH http://localhost:3005/courses/2
Content-Type: application/json

{
    "title": "Cardio Intensif"
}

### delete course
DELETE http://localhost:3005/courses/2

### test import api courses
POST http://localhost:3005/courses/import

### Créer une réservation
POST http://localhost:3005/reservations
Content-Type: application/json

{
  "courseId": 2
}
### Voir toutes les réservations
GET http://localhost:3005/reservations

### Voir mes réservations
GET http://localhost:3005/reservations/user

### Annuler une réservation
DELETE http://localhost:3005/reservations/2

### S'inscrire sur la liste d'attente
POST http://localhost:3005/wait-list
Content-Type: application/json

{
     "courseId": 2 
}

### Voir la liste d'attente d'un cours
GET http://localhost:3005/waitlist/course/2

### Voir mes listes d'attente
GET http://localhost:3005/wait-list/user

### Se retirer de la liste d'attente
DELETE http://localhost:3005/waitlist/1