### test signup user with unique email
POST  http://localhost:3000/auth/signup
Content-Type: application/json
 
{
   
    "email": "saraaissat@hotmail.com",
    "password": "mdp"
}

 
### test who is signin
GET http://localhost:3000/auth/whoami
 
### test login user with correct credentials
POST http://localhost:3000/auth/signin
Content-Type: application/json
 
{
    "email": "alben2@hotmail.com",
    "password": "mdp"
}
 
### test all users
GET http://localhost:3000/auth
 
### tester route get user by id
GET http://localhost:3000/auth/5
 
### test signout user
POST http://localhost:3000/auth/signout

### delete user 
DELETE  http://localhost:3000/auth/9
 